name: Build React App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build
        run: |
          npm ci
          npm run build
        env:
          REACT_APP_GITHUB_TOKEN: ${{ secrets.CHRISTMAS_GIST_TOKEN }}

    - name: Commit and push if changed
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add docs/
        git diff --staged --quiet || git commit -m "Auto-build: Update docs folder"
        git push